# Generated by Django 4.1.6 on 2023-02-09 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='produto')),
                ('describe', models.TextField(verbose_name='descrição')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='preço')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='estoque')),
            ],
            options={
                'verbose_name': 'produto',
            },
        ),
    ]
