# Generated by Django 4.1.6 on 2023-02-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='products/', verbose_name='imagem'),
            preserve_default=False,
        ),
    ]
