# Generated by Django 4.1.6 on 2023-02-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
