# Generated by Django 4.1.6 on 2023-02-09 23:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('subtotal', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='sub-total')),
                ('freight', models.FloatField(verbose_name='frete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'carrinho',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitary_value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor unitário')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='quantidade')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.cart', verbose_name='carrinho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item do carrinho',
            },
        ),
    ]
