# Generated by Django 4.1.6 on 2023-02-10 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='freight',
            field=models.FloatField(default=0, verbose_name='frete'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('W', 'Esperando'), ('A', 'Abandonado'), ('F', 'Finalizado')], default='W', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sub-total'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
    ]
