# Generated by Django 4.1.6 on 2023-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_freight_alter_cart_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='subtotal',
        ),
    ]
